version: '3.8'

services:
  # ✅ MinIO
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # ✅ Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # ✅ Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ✅ Spark Master
  spark-master:
    image: bitnami/spark:3.4
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_SUBMIT_OPTIONS=--packages org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.4.3
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./api/spark_jobs:/app/spark_jobs
      - ./api/spark_jobs/jars:/opt/bitnami/spark/extra-jars

    command:
      - bash
      - -c
      - |
          echo '▶ Выполнение инициализации...'
          /opt/bitnami/spark/bin/spark-submit \
            --master local \
            --jars /opt/bitnami/spark/extra-jars/iceberg-spark-runtime-3.4_2.12-1.4.3.jar \
            /app/spark_jobs/init_products_table.py
          echo '▶ Запуск Spark Master...'
          /opt/bitnami/scripts/spark/entrypoint.sh /opt/bitnami/scripts/spark/run.sh


  # ✅ Spark Worker
  spark-worker:
    image: bitnami/spark:3.4
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./api/spark_jobs:/app/spark_jobs
      - ./api/spark_jobs/jars:/opt/bitnami/spark/extra-jars

  # ✅ FastAPI + Docker CLI
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./api/spark_jobs:/app/spark_jobs
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 доступ к Docker хоста
    depends_on:
      - kafka
      - minio
      - spark-master
    environment:
      PYTHONUNBUFFERED: 1

volumes:
  minio_data:
